[build]
  command = "yarn build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.19.0"
  PYTHON_VERSION = "3.12"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
